import { reverse } from "dns";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const habits = ["Read", "Meditate", "Sleep"];

const getLast11Days = () => {
  const today = new Date();
  const last11Days = [];

  for (let i = 0; i < 11; i++) {
    const day = today.getDate();
    last11Days.push(day);

    // Move the date one day back for the next iteration
    today.setDate(day - 1);
  }
  last11Days.reverse();
  return last11Days;
};

const CreateHabit = () => {
  return (
    <div className="grid h-16 w-full grid-cols-12 items-center">
      <div className="w-40 pl-8 text-neutral-400">Add item</div>
    </div>
  );
};

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const last11Days = getLast11Days();

  return (
    <>
      <Head>
        <title>Habit Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen  divide-y-4 divide-dashed bg-neutral-100">
        <div className="grid grid-cols-12">
          <div></div>

          {last11Days.map((day, index) => (
            <span
              key={index}
              className={`flex h-16 items-center justify-center`}
            >
              {day}
            </span>
          ))}
        </div>

        <div>
          {habits.map((habit, index) => (
            <div
              key={index}
              className="grid h-16 w-full grid-cols-12 items-center"
            >
              <div className="w-40 pl-8">{habit}</div>

              {last11Days.map((day, index) => (
                <div
                  key={index}
                  className="form-control h-full items-center justify-center"
                >
                  <label className="label h-2/3 w-2/3 cursor-pointer justify-center">
                    <input
                      type="checkbox"
                      className="checkbox-success checkbox"
                    />
                  </label>
                </div>
              ))}
            </div>
          ))}
          <CreateHabit />
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
